# Generated by Django 2.2.10 on 2024-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
